### ISSUE TITLE
无法预览

### ISSUE THREAD

**Issue by lewis-ing** [Orginly/renting_minapp#2]
请问一下，您的小程序是否可以预览

**Comment by Orginly** [comment]
现在上班没时间更新了

**Comment by lewis-ing** [comment]
方便能让我看一下吗？谢谢了

**Comment by Orginly** [comment]
晚上有空先吧

**Comment by lewis-ing** [comment]
好的，谢谢了，到时候等你联系，我的微信是：275498012，谢谢。

**Comment by lewis-ing** [comment]
在吗？方便调试一下吗？

**Comment by Orginly** [comment]
![image](https://user-images.githubusercontent.com/58434904/97575317-84439380-1a27-11eb-96ab-aab5bef5c4d7.png)
大概样子是这样的，只做了静态页功能还没时间做

**Comment by lewis-ing** [comment]
看不到，能截图发我一下吗？或叫我微信发一下看看，谢谢

**Comment by Orginly** [comment]
我加了
